#!/usr/bin/env ansible-playbook

- hosts: localhost
  connection: local

  vars:
#    instance_id: 'i-049397357e6b367ea'
    instance_id: 'i-0a8e24b6d361063a7'

  tasks:

  - name: create ec2 volume
    ec2_vol:
      instance: "{{ instance_id }}"
      volume_size: 200
      volume_type: gp3
      device_name: /dev/sdf
      zone: "ap-southeast-1a"
      region: "ap-southeast-1"
